### ISSUE TITLE
Shops not (truly) randomised.

### ISSUE THREAD

**Issue by AvatarMew** [abyssonym/approaching_chaos#1]
I've tested this randomiser a few times and none of the shops are really randomised in FF1.
The shops in the first town only have one random item and the magic shops are not randomised.
The prices seem to be randomised however.

Also, the monsters can't be randomised either.

**Comment by abyssonym** [comment]
Shop inventories & monsters on the extreme low end and high end are very resistant to randomization, to keep the game somewhat balanced and playable. If you keep playing you'll see more significant randomizations in the midgame.

However, if you're not concerned with game balance, you can use a higher "randomness" value. Using a value of 0.75 might be a good place to start; 1.0 is the maximum and it just randomizes everything without paying attention to balance at all. If you use the "custom" keyword, you can set different randomness values for different parts of the game. For example, you might want to make shops 100% random but not enemies.
